---
name: learn-bosh
director_uuid: 17a45148-1d00-43bc-af28-9882e5a6535a

releases:
- name: learn-bosh
  version: latest

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: app
  templates:
  - name: app
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.0.2
  properties: {}
